// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlzofxL6X_BqqH2e3bwvAtGgFX4UdJfKw',
    appId: '1:880678435091:android:c3dd5e72c141c6562182e6',
    messagingSenderId: '880678435091',
    projectId: 'tugasflutter-8156f',
    storageBucket: 'tugasflutter-8156f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaPLGAko63IXpAAmr8QhOyzw7B0o3xA70',
    appId: '1:880678435091:ios:989d36b0ec665c8d2182e6',
    messagingSenderId: '880678435091',
    projectId: 'tugasflutter-8156f',
    storageBucket: 'tugasflutter-8156f.firebasestorage.app',
    iosBundleId: 'com.example.tugasFlutter',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ12H5wQfm0CbDtqREJg2YJ4hYkpGYZpY',
    appId: '1:880678435091:web:4aeb3473658adaff2182e6',
    messagingSenderId: '880678435091',
    projectId: 'tugasflutter-8156f',
    authDomain: 'tugasflutter-8156f.firebaseapp.com',
    storageBucket: 'tugasflutter-8156f.firebasestorage.app',
    measurementId: 'G-Y3J8T7LFJM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaPLGAko63IXpAAmr8QhOyzw7B0o3xA70',
    appId: '1:880678435091:ios:989d36b0ec665c8d2182e6',
    messagingSenderId: '880678435091',
    projectId: 'tugasflutter-8156f',
    storageBucket: 'tugasflutter-8156f.firebasestorage.app',
    iosBundleId: 'com.example.tugasFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ12H5wQfm0CbDtqREJg2YJ4hYkpGYZpY',
    appId: '1:880678435091:web:7a1a95544c67a37e2182e6',
    messagingSenderId: '880678435091',
    projectId: 'tugasflutter-8156f',
    authDomain: 'tugasflutter-8156f.firebaseapp.com',
    storageBucket: 'tugasflutter-8156f.firebasestorage.app',
    measurementId: 'G-YDJZ0QCD3T',
  );

}